### ISSUE TITLE
TypedMiddleware not accept specified middleware type.

### ISSUE THREAD

**Issue by jaggerwang** [johnpryan/redux.dart#35]
## Problem

When specify the exact action type, TypedMiddleware complains `[dart] The return type '(Store<AppState>, LoginAction, (dynamic) → void) → Null' isn't a '(Store<AppState>, dynamic, (dynamic) → void) → void', as defined by the method 'loginMiddleware'.`.

## Code

```dart
List<Middleware<AppState>> createMiddlewares({
  AccountService accountService,
}) {
  accountService = accountService ?? AccountService();

  return [
    TypedMiddleware<AppState, LoginAction>(loginMiddleware(accountService)),
  ];
}

Middleware<AppState> loginMiddleware(AccountService accountService) =>
    // Specify the exact type of action, not dynamic
    (Store<AppState> store, LoginAction action, NextDispatcher next) {
      next(action);
    };
```

## Env

```yaml
name: tangbole
description: A tumblr client app.

dependencies:
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.1
  http: ^0.11.3+16
  meta: ^1.1.5
  uri: ^0.11.2
  redux: ^3.0.0
  redux_logging: ^0.3.0
  redux_persist: ^0.7.0-rc.2
  redux_persist_flutter: ^0.6.0-rc.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg

```
